CREATE DATABASE IF NOT EXISTS naser_sgi CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE naser_sgi;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS operaciones; DROP TABLE IF EXISTS usuario_sector; DROP TABLE IF EXISTS documentos; DROP TABLE IF EXISTS usuarios; DROP TABLE IF EXISTS zonas; DROP TABLE IF EXISTS sectores;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE sectores(id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(100) NOT NULL,slug VARCHAR(80) NOT NULL UNIQUE,orden INT NOT NULL DEFAULT 0) ENGINE=InnoDB;
CREATE TABLE zonas(id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(100) NOT NULL UNIQUE,activa TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB;
CREATE TABLE usuarios(id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(100) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,rol ENUM('admin','supervisor','ventas','operador') NOT NULL,zona_id INT NULL,activo TINYINT(1) NOT NULL DEFAULT 1,creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(zona_id) REFERENCES zonas(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE usuario_sector(usuario_id INT NOT NULL,sector_id INT NOT NULL,puede_ver TINYINT(1) NOT NULL DEFAULT 1,puede_editar TINYINT(1) NOT NULL DEFAULT 0,PRIMARY KEY(usuario_id,sector_id),FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,FOREIGN KEY(sector_id) REFERENCES sectores(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE documentos(id INT AUTO_INCREMENT PRIMARY KEY,sector_id INT NOT NULL,titulo VARCHAR(180) NOT NULL,descripcion TEXT NULL,tipo ENUM('documentacion','procedimiento') NOT NULL,archivo VARCHAR(255) NULL,activo TINYINT(1) NOT NULL DEFAULT 1,fecha_actualizacion DATE NOT NULL,creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(sector_id) REFERENCES sectores(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE operaciones(id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(160) NOT NULL,descripcion TEXT NULL,zona_id INT NULL,estado ENUM('activa','inactiva') NOT NULL DEFAULT 'activa',orden INT NOT NULL DEFAULT 0,FOREIGN KEY(zona_id) REFERENCES zonas(id) ON DELETE SET NULL) ENGINE=InnoDB;
INSERT INTO sectores(nombre,slug,orden) VALUES ('Seguridad','seguridad',1),('Mantenimiento','mantenimiento',2),('Operaciones','operaciones',3),('Recursos Humanos','rrhh',4),('Finanzas','finanzas',5),('Compras','compras',6),('Gerencia','gerencia',7);
INSERT INTO zonas(nombre) VALUES ('Zona 1'),('Zona 2'),('Zona 3'),('Zona 4'),('Zona 5'),('Zona 6'),('Zona 7'),('Zona 8');
INSERT INTO operaciones(nombre,descripcion,zona_id,orden) VALUES
('Slickline','Operaciones de Slickline y trabajos asociados.',NULL,1),('Well Testing','Pruebas de pozo, mediciones y control operativo.',NULL,2),('Flowback','Operaciones de flowback y control de retorno.',NULL,3),('Armado y desarmado de equipos','Preparación, montaje y desmontaje de equipos en locación.',NULL,4),('Control de herramientas','Chequeo de herramientas antes y después de cada servicio.',NULL,5),('Inspección preoperacional','Verificaciones de seguridad previas a la tarea.',NULL,6),('Registro de parámetros','Carga de presiones, tiempos, caudales y observaciones.',NULL,7),('Cierre de operación','Cierre documental y reporte final del servicio.',NULL,8);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Administrador General','admin1@naser.com','$2y$12$EAL1ydrIaipsjcLwynMdB.N3hgZB2x7kfJ2NqDZhk2dlUtDfcNGKO','admin',NULL,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Administrador SGI','admin2@naser.com','$2y$12$m9P3wv3K63m9/VNqVR9/seJz3V4ASZuZXPhIwk74AB69d2gNXYwNm','admin',NULL,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Administrador Sistemas','admin3@naser.com','$2y$12$zsiH.XpNPNKjf3fGpWTabOjlpFATfXUMS5j1LyIT6tcxqDs/Cm8ma','admin',NULL,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Supervisor Zona 1','supervisor1@naser.com','$2y$12$4CPokA2PU1CjKerEfs.xb.Qze5m/q4ZQ..pWzpivSDk/lH9JsZyJ2','supervisor',1,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Supervisor Zona 2','supervisor2@naser.com','$2y$12$ifum25EAsgkWC7cYzgq1kO4lPGP9Rp0f92Sa1nfw4.0SnsyBtv.8W','supervisor',2,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Supervisor Zona 3','supervisor3@naser.com','$2y$12$KNATcm/6.SIqmDrfB02dsObzvsoB8OmRcaGQdidXJwXlh7O4ruJ8W','supervisor',3,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Supervisor Zona 4','supervisor4@naser.com','$2y$12$UH6WUcf01lFc9e32/jY2AOUiR81J7c4GpsjJA.QDzkBeQOQlOu6pK','supervisor',4,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Supervisor Zona 5','supervisor5@naser.com','$2y$12$43Q7FTKE.UQ3tJr47snLH.R2boDvqeHju4rwIaZykQIY0LwUY.Kcm','supervisor',5,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Supervisor Zona 6','supervisor6@naser.com','$2y$12$kI9M9NxaeTEhf2BR1M5syO6ZtBomKIbTmqfhRO3pLcD00Gex7mwVi','supervisor',6,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Supervisor Zona 7','supervisor7@naser.com','$2y$12$.PxeuOD/A9eoH/SoBBzXQ.FDXZk6eAjq7hyuCff6ylL//MQePLGgq','supervisor',7,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Supervisor Zona 8','supervisor8@naser.com','$2y$12$7Ak/YvqMKGeUL7ZkOkrWJecG477CPDbxgCET9yENUHOtX2FchXKhS','supervisor',8,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Usuario Ventas','ventas@naser.com','$2y$12$bBz/k2XCMabnbgmeNTxgP.O17cz7pqVjrJJaBhPxAxlO0PjRgkzl.','ventas',NULL,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 01','operador01@naser.com','$2y$12$VDtckwfF1.TFpiQxRmlG1O4slcewNzMrMmhsyg5Ag2YO8x/xfuM3G','operador',1,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 02','operador02@naser.com','$2y$12$4VQJ09a0qv6kpTyGSIRsBub3NrNmy1pO5o9br7EreRJaNri8mbCUC','operador',2,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 03','operador03@naser.com','$2y$12$9ubm4cgy7NX62Q9sto9jPuBocwNWNormy27KamtmO3vCV/oOFu4U2','operador',3,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 04','operador04@naser.com','$2y$12$j22LTnYa1oH7vBQDHY0K2OpDPv3MPtkaRJgJ3FbaKbWx.zTZi7bxO','operador',4,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 05','operador05@naser.com','$2y$12$UUuGmR24vzqnNxYauEAoHus0ctBsXOX1AbUdmTmrhTVFe7vKbKtrC','operador',5,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 06','operador06@naser.com','$2y$12$rIQIwMAMor0KTLa2bRHqd.He/N2VnI3jreZ0b0kyR7hPITCsQ8jHy','operador',6,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 07','operador07@naser.com','$2y$12$ZQnW03M7jjUlUvQvAnfy/uqUEP0BrbNUhoSxj5itnHTT.PcrS7UNu','operador',7,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 08','operador08@naser.com','$2y$12$gVJ5s/8mCOUrDfnAiL0uxeWNt7JLm5M/UeckU4eTQWlAwhqhcJXi.','operador',8,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 09','operador09@naser.com','$2y$12$MSvSLbNIJNb1gCLbV8W51O4P5ikpxIRmSHLLiml8pYER.IOqZPC/W','operador',1,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 10','operador10@naser.com','$2y$12$0YRrC6C1ykCRmPo9yjoubOqAClW0T/l7DCa2a6LV75jDIw89WsWQ2','operador',2,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 11','operador11@naser.com','$2y$12$tcWwnXegTugixGc5mQJ24uwK2WdyTQsxr6At.M8NNyEJir2Tx0JsO','operador',3,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 12','operador12@naser.com','$2y$12$VMwgV3r3uWXs6LV7TG3fb.JqTIePdvINCbU1ge1WPChnA.Zdha8Wi','operador',4,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 13','operador13@naser.com','$2y$12$QLDlWBpGFBFvU2WRStOi0u9LlCaDz6Bl8Djyz3SrHsbq7ODsC2EBe','operador',5,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 14','operador14@naser.com','$2y$12$wKv3Mmclkqu.sDY8M.OpgerRzLL/FQ6.stF0XmqIfW0e5arWraMdC','operador',6,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 15','operador15@naser.com','$2y$12$2Dq0FF6/3j0GnRTIBudhMef.e9P90/kAWuKVdD4sQoMCs92lZfKr.','operador',7,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 16','operador16@naser.com','$2y$12$CofOS.thAQVC92AFe24s4.Sd6F67ZBveWL5a4jQGjsdn8aXZPBjJa','operador',8,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 17','operador17@naser.com','$2y$12$P1cYFGVoMuNIUXeBuEpH5O8l1Oo9UpKGV0hqquDn/xMZBnEwPx.Z2','operador',1,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 18','operador18@naser.com','$2y$12$NJGI4T8wRKiUnoEU9erutuAdF4lufRLgJ7tuyNf/lY6qhclFNUuBu','operador',2,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 19','operador19@naser.com','$2y$12$yQheQS9NQBR04aCDee.bWuD1F.SocKmpfHVOTj.nqRVOXdYzsw6IG','operador',3,1);
INSERT INTO usuarios(nombre,email,password,rol,zona_id,activo) VALUES ('Operador 20','operador20@naser.com','$2y$12$hToYY1627I0njirzL01PGOZ74KUyysCDM7jBgXb27WvN38S1hVIvG','operador',4,1);

INSERT INTO usuario_sector SELECT u.id,s.id,1,1 FROM usuarios u CROSS JOIN sectores s WHERE u.rol='admin';
INSERT INTO usuario_sector SELECT u.id,s.id,1,1 FROM usuarios u JOIN sectores s ON s.slug IN ('operaciones','seguridad','mantenimiento') WHERE u.rol='supervisor';
INSERT INTO usuario_sector SELECT u.id,s.id,1,0 FROM usuarios u JOIN sectores s ON s.slug IN ('operaciones','finanzas','gerencia') WHERE u.rol='ventas';
INSERT INTO usuario_sector SELECT u.id,s.id,1,0 FROM usuarios u JOIN sectores s ON s.slug IN ('operaciones','seguridad') WHERE u.rol='operador';
