<?php
require __DIR__.'/config/auth.php';requireLogin();require __DIR__.'/config/db.php';require __DIR__.'/config/layout.php';
$slug=trim($_GET['sector']??'');$cid=!empty($_GET['carpeta'])?(int)$_GET['carpeta']:null;$q=trim($_GET['q']??'');
$st=$pdo->prepare('SELECT * FROM sectores WHERE slug=? LIMIT 1');$st->execute([$slug]);$s=$st->fetch();if(!$s)exit('Sector no encontrado');if(!puedeVerSector($pdo,$s['id'])){http_response_code(403);exit('Sin acceso');}
if($cid){$st=$pdo->prepare('SELECT * FROM carpetas WHERE sector_id=? AND carpeta_padre_id=? AND activa=1 ORDER BY orden,nombre');$st->execute([$s['id'],$cid]);}else{$st=$pdo->prepare('SELECT * FROM carpetas WHERE sector_id=? AND carpeta_padre_id IS NULL AND activa=1 ORDER BY orden,nombre');$st->execute([$s['id']]);}$folders=$st->fetchAll();
$sql='SELECT * FROM documentos WHERE sector_id=? AND activo=1';$params=[$s['id']];if($cid){$sql.=' AND carpeta_id=?';$params[]=$cid;}else{$sql.=' AND carpeta_id IS NULL';}if($q!==''){$sql.=' AND (titulo LIKE ? OR descripcion LIKE ?)';$like='%'.$q.'%';$params[]=$like;$params[]=$like;}$sql.=' ORDER BY titulo';$st=$pdo->prepare($sql);$st->execute($params);$docs=$st->fetchAll();
?><!doctype html><html lang="es"><head><meta charset="utf-8"><link rel="stylesheet" href="../style.css"></head><body><div class="app"><?php sidebar($pdo,$s['slug']);?><main class="content"><header class="section-top"><div><p class="eyebrow">SECTOR</p><h1><?=htmlspecialchars($s['nombre'])?></h1><p>Carpetas, documentos y procedimientos.</p></div></header>
<form method="get" class="form-row" style="grid-template-columns:1fr auto;margin-bottom:18px"><input type="hidden" name="sector" value="<?=htmlspecialchars($slug)?>"><?php if($cid):?><input type="hidden" name="carpeta" value="<?=$cid?>"><?php endif;?><input name="q" value="<?=htmlspecialchars($q)?>" placeholder="Buscar..."><button class="btn primary">Buscar</button></form>
<div class="section-head"><div><p class="eyebrow">CARPETAS</p><h2>Explorar</h2></div></div><section class="sector-grid"><?php foreach($folders as $f):?><article class="sector-card"><div class="sector-code">📁</div><h3><?=htmlspecialchars($f['nombre'])?></h3><p>Carpeta documental.</p><div class="card-links"><a href="sector.php?sector=<?=urlencode($slug)?>&carpeta=<?=$f['id']?>">Abrir →</a></div></article><?php endforeach;?></section>
<div class="section-head"><div><p class="eyebrow">ARCHIVOS</p><h2>Documentos</h2></div></div><section class="document-grid"><?php if(!$docs):?><div class="empty">No hay archivos.</div><?php endif;?><?php foreach($docs as $d):?><article class="document-card"><span class="type-badge"><?=htmlspecialchars(ucfirst($d['tipo']))?></span><h3><?=htmlspecialchars($d['titulo'])?></h3><p>Versión <?=htmlspecialchars($d['version']??'1.0')?> · <?=htmlspecialchars($d['estado']??'aprobado')?></p><?php if($d['archivo']):?><div class="doc-actions"><a class="btn secondary" href="../uploads/<?=rawurlencode($d['archivo'])?>" target="_blank">Abrir</a></div><?php endif;?></article><?php endforeach;?></section></main></div></body></html>